name: Build and Release

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: 'update version'
      shell: bash
      run: |
        buildDateNumber=$(date '+%Y.%m.%d')
        buildId=$GITHUB_RUN_NUMBER
        buildNumber="$buildDateNumber.$buildId"
        echo "$buildNumber"
        projContent=$(sed "s+<Version>[0-9][0-9]*.*[0-9]*.*[0-9]*.*</Version>+<Version>$buildNumber</Version>+g" HostedApp.csproj)
        echo "$projContent" > HostedApp.csproj
      working-directory: src/HostedApp
    
    - name: Install dependencies
      run: dotnet restore /nologo
      working-directory: AzDOBulkUpdateClassicReleaseStageTimeouts
    - name: Build
      run: dotnet build --configuration Release --no-restore /nologo
      working-directory: AzDOBulkUpdateClassicReleaseStageTimeouts
    - name: Test
      run: dotnet test --no-restore --no-build --verbosity normal /nologo
      working-directory: AzDOBulkUpdateClassicReleaseStageTimeouts
    - name: Publish
      run: dotnet publish --configuration Release --no-restore --no-build --output "../package" --verbosity normal /nologo /property:GenerateFullPaths=true
      working-directory: AzDOBulkUpdateClassicReleaseStageTimeouts

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          
        draft: false
        prerelease: false
